homepage:
    path: /
    defaults:
        _controller: App\Controller\MainController::homepageAction

controllers:
    resource: "../src/Controller/"
    type: annotation

login:
    path: /login
    controller: App\Controller\SecurityController::login
