homepage:
    path: /
    defaults:
        _controller: App\Controller\MainController::homepageAction

controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    controller: App\Controller\Security\SecurityController::login
